name: Docker Image CI

on:
  push:
    branches: [ "release-5.26.0" ]
  pull_request:
    branches: [ "release-5.26.0" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      NEO4JVERSION: 5.26.0
    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: make build-debian-community

      - name: Push the Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/shouqianba-ft/neo4j:${{ NEO4JVERSION }}-community


